
# Site settings
title: LakeWater Economics Blog
email: mcsammon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Opinions of a finance PhD student whose office happens to overlook Lake Michigan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcosammon.com" # the base hostname & protocol for your site
future: true
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
