
# Site settings
title: Marco Sammon
email: mcsammon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright Marco Sammon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcosammon.com" # the base hostname & protocol for your site
future: true
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
